<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Option;
use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $categories = $this->seedCategories();
        $this->seedQuestions($categories);
        $this->command->info('Seeded 400 questions across 5 categories.');
    }

    private function seedCategories(): array
    {
        $data = [
            ['name' => 'Road Signs',         'slug' => 'road-signs',       'icon' => '🚸', 'description' => 'Traffic signs, warning signs, and regulatory signs'],
            ['name' => 'Traffic Rules',       'slug' => 'traffic-rules',    'icon' => '📋', 'description' => 'Laws and regulations governing road use'],
            ['name' => 'Vehicle Control',     'slug' => 'vehicle-control',  'icon' => '🚗', 'description' => 'Safe vehicle operation and handling'],
            ['name' => 'Road Safety',         'slug' => 'road-safety',      'icon' => '⛑️',  'description' => 'Safety practices and accident prevention'],
            ['name' => 'First Aid & Emergencies', 'slug' => 'first-aid',   'icon' => '🚑', 'description' => 'Emergency response and basic first aid'],
        ];

        $categories = [];
        foreach ($data as $cat) {
            $categories[$cat['slug']] = Category::firstOrCreate(
                ['slug' => $cat['slug']],
                $cat
            );
        }

        return $categories;
    }

    private function seedQuestions(array $categories): void
    {
        $questions = $this->getQuestionBank($categories);

        foreach ($questions as $qData) {
            $question = Question::create([
                'category_id'   => $qData['category_id'],
                'question_text' => $qData['question'],
                'difficulty'    => $qData['difficulty'],
                'explanation'   => $qData['explanation'],
                'is_active'     => true,
            ]);

            foreach ($qData['options'] as $index => $opt) {
                Option::create([
                    'question_id' => $question->id,
                    'option_text' => $opt['text'],
                    'is_correct'  => $opt['correct'],
                    'order'       => $index,
                ]);
            }
        }
    }

    private function getQuestionBank(array $cats): array
    {
        $rs = $cats['road-signs']->id;
        $tr = $cats['traffic-rules']->id;
        $vc = $cats['vehicle-control']->id;
        $safety = $cats['road-safety']->id;
        $fa = $cats['first-aid']->id;

        // Helper to build a question row
        $q = fn($cat, $question, $opts, $correct, $diff, $exp) => [
            'category_id' => $cat,
            'question'    => $question,
            'difficulty'  => $diff,
            'explanation' => $exp,
            'options'     => collect($opts)->map(fn($o, $i) => [
                'text'    => $o,
                'correct' => $i === $correct,
            ])->values()->all(),
        ];

        return [
            // ── ROAD SIGNS (80 questions) ─────────────────────────────────────
            $q($rs, 'What does a red octagonal sign mean?', ['Stop completely', 'Slow down', 'Yield', 'No entry'], 0, 'easy', 'A red octagon always means STOP — you must come to a complete stop.'),
            $q($rs, 'A triangular sign with a red border and white background is:', ['A warning sign', 'A regulatory sign', 'An information sign', 'A directional sign'], 0, 'easy', 'Triangular signs with red borders are warning signs indicating hazards ahead.'),
            $q($rs, 'What does a blue circular sign indicate?', ['Mandatory instruction', 'Warning', 'Information only', 'Prohibition'], 0, 'medium', 'Blue circular signs give mandatory instructions that must be followed.'),
            $q($rs, 'A yellow diamond-shaped sign warns you about:', ['Road hazards ahead', 'Speed limits', 'Directions to follow', 'No parking zones'], 0, 'easy', 'Yellow diamond signs are warning signs alerting you to road hazards.'),
            $q($rs, 'What does a sign showing a crossed-out "P" mean?', ['No parking allowed', 'Parking only', 'Paid parking', 'Priority parking'], 0, 'easy', 'A crossed-out "P" means parking is prohibited in that area.'),
            $q($rs, 'A white rectangular sign with black text usually provides:', ['Information or guidance', 'Strict regulations', 'Emergency instructions', 'Speed restrictions only'], 0, 'easy', 'White rectangular signs with black text are informational or guide signs.'),
            $q($rs, 'What does a sign with two arrows pointing in opposite directions mean?', ['Two-way traffic ahead', 'One-way road ends', 'Road closed', 'Merge ahead'], 0, 'medium', 'This sign warns that two-way traffic is present or begins ahead.'),
            $q($rs, 'A sign showing a person walking indicates:', ['Pedestrian crossing ahead', 'School zone', 'No pedestrians', 'Walking trail'], 0, 'easy', 'This warning sign tells drivers a pedestrian crossing is ahead.'),
            $q($rs, 'What does a red circle with a diagonal line through a symbol mean?', ['That action is prohibited', 'That action is mandatory', 'That action is recommended', 'Warning of danger'], 0, 'easy', 'A red circle with diagonal line (prohibition sign) means the action is forbidden.'),
            $q($rs, 'The sign showing a truck on a slope means:', ['Steep hill ahead', 'Trucks only lane', 'No trucks allowed', 'Truck loading zone'], 0, 'medium', 'This sign warns of a steep gradient ahead, particularly relevant for heavy vehicles.'),
            $q($rs, 'A sign with a "!" (exclamation) in a triangle warns:', ['General hazard ahead', 'Stop required', 'Speed bump', 'Railway crossing'], 0, 'easy', 'An exclamation mark in a warning triangle indicates a general hazard.'),
            $q($rs, 'What does a green sign with an arrow typically indicate?', ['Direction to a destination', 'Mandatory turn', 'No entry', 'Speed limit'], 0, 'easy', 'Green directional signs guide drivers toward destinations and junctions.'),
            $q($rs, 'A zigzag line painted on the road near a crossing means:', ['No stopping or parking', 'Slow down area', 'School zone boundary', 'Bus stop zone'], 0, 'medium', 'Zigzag markings near crossings prohibit stopping and parking to keep crossing visible.'),
            $q($rs, 'What does a sign with two cars side by side (one red, one blue) indicate?', ['Overtaking is prohibited', 'Use both lanes', 'Lane merge ahead', 'Car park entrance'], 0, 'medium', 'This sign prohibits overtaking — passing another vehicle is not allowed.'),
            $q($rs, 'A "Give Way" sign requires you to:', ['Yield to traffic on the main road', 'Stop completely before proceeding', 'Speed up to merge', 'Flash your lights'], 0, 'easy', 'Give Way means yield — slow down and give priority to crossing traffic.'),
            $q($rs, 'What does a railway level crossing sign with flashing red lights mean?', ['Stop — a train is approaching', 'Slow down only', 'Proceed with caution', 'The crossing is clear'], 0, 'easy', 'Flashing red lights at a railway crossing mean a train is coming — STOP.'),
            $q($rs, 'A sign showing a car skidding indicates:', ['Slippery road ahead', 'Test your brakes', 'Rough road surface', 'Sharp bend'], 0, 'easy', 'The skidding car symbol warns of slippery surface conditions ahead.'),
            $q($rs, 'What does a "No Entry" sign look like?', ['Red circle with horizontal white bar', 'Red triangle with X', 'Blue circle with arrow', 'White rectangle with red text'], 0, 'easy', 'A "No Entry" sign is a red circle containing a horizontal white rectangle.'),
            $q($rs, 'A sign with cattle or livestock warns:', ['Animals may be on the road', 'Slaughterhouse ahead', 'No animals allowed', 'Wildlife reserve'], 0, 'easy', 'Livestock warning signs alert drivers that animals may cross or be on the road.'),
            $q($rs, 'What does a speed limit sign (e.g. "50") inside a red circle mean?', ['Maximum speed is 50 km/h', 'Minimum speed is 50 km/h', 'Average speed check', 'Recommended speed'], 0, 'easy', 'Speed limit signs in red circles show the maximum legal speed in km/h.'),
            // 20 more road signs questions...
            $q($rs, 'A sign showing children running warns you:', ['School or playground ahead', 'No children allowed', 'Day care centre', 'Sports field'], 0, 'easy', 'This warning sign tells drivers there may be children near the road.'),
            $q($rs, 'What does a white arrow on a blue background mean?', ['You must follow that direction', 'Recommended direction', 'One-way information', 'Emergency exit'], 0, 'medium', 'White arrow on blue = mandatory direction — you must go that way.'),
            $q($rs, 'A sign with a bicycle inside a red circle means:', ['No cycling allowed', 'Cycling lane', 'Bicycle parking', 'Caution: cyclists'], 0, 'easy', 'A bicycle in a red circle prohibits cyclists from using that road.'),
            $q($rs, 'What does a "Roundabout" sign (circular arrows) indicate?', ['A roundabout junction ahead', 'U-turns permitted', 'Traffic calming zone', 'Circular road'], 0, 'easy', 'The roundabout sign warns that a roundabout intersection is approaching.'),
            $q($rs, 'A broken white line in the centre of the road means:', ['Overtaking is permitted when safe', 'No overtaking', 'Lane ends', 'Road narrows'], 0, 'medium', 'Broken centre lines allow overtaking when it is safe to do so.'),
            $q($rs, 'A solid yellow line along the kerb means:', ['No parking at any time', 'Parking limited to 1 hour', 'Loading only zone', 'Disabled parking'], 0, 'medium', 'A solid yellow kerb line prohibits parking at all times.'),
            $q($rs, 'What does a "T-junction" sign warn?', ['The road ends at a junction ahead', 'Three-way merge', 'Tunnel ahead', 'Traffic lights ahead'], 0, 'easy', 'A T-junction sign warns that the road you are on ends at a T intersection.'),
            $q($rs, 'A sign with a bridge and height restriction (e.g. "3.5m") means:', ['Vehicles over 3.5m must not use this road', 'Bridge weight limit', 'Speed limit on bridge', 'Bridge under construction'], 0, 'medium', 'Height restriction signs protect bridges — vehicles exceeding the height must not pass.'),
            $q($rs, 'What does a road narrows sign (funnel shape) warn?', ['The road becomes narrower ahead', 'Lane merging from one side', 'Both sides reduce', 'All of the above depending on which sides are shown'], 3, 'medium', 'Road narrows signs can show narrowing from left, right, or both sides.'),
            $q($rs, 'A "No U-Turn" sign means:', ['U-turns are prohibited', 'U-turns are mandatory', 'Reversing allowed', 'Three-point turns only'], 0, 'easy', 'No U-Turn signs prohibit vehicles from making a U-turn at that location.'),
            $q($rs, 'A sign showing falling rocks warns:', ['Rockfall or landslide hazard', 'Quarry entrance', 'Unpaved road', 'Mining area'], 0, 'medium', 'Falling rocks signs warn of areas prone to rockfall or loose material.'),
            $q($rs, 'What does a pedestrian refuge island sign indicate?', ['A safe crossing island exists in road', 'Pedestrians prohibited', 'Median strip', 'Bus shelter'], 0, 'medium', 'This sign marks where pedestrian refuge islands divide multi-lane crossings.'),
            $q($rs, 'A "Road Works" or construction sign requires you to:', ['Slow down and drive carefully', 'Stop until workers signal', 'Change lanes immediately', 'Honk to alert workers'], 0, 'easy', 'Road works signs warn drivers to slow down and proceed with extra caution.'),
            $q($rs, 'What does a hospital sign (H in blue) tell drivers?', ['Hospital is nearby', 'First aid post ahead', 'Emergency U-turn permitted', 'Ambulance station'], 0, 'easy', 'The blue H sign directs drivers to a hospital or medical facility.'),
            $q($rs, 'A sign showing a fuel pump indicates:', ['Petrol station ahead', 'No fuel vehicles', 'Electric charging point', 'Emergency fuel only'], 0, 'easy', 'Fuel pump signs direct drivers to nearby service/petrol stations.'),
            $q($rs, 'What does a "No Overtaking Trucks" sign show?', ['A car overtaking a red truck, with a line through it', 'Two trucks side by side', 'Truck speed limit', 'Truck lane only'], 0, 'medium', 'This sign specifically prohibits heavy goods vehicles from overtaking.'),
            $q($rs, 'An amber/orange traffic light means:', ['Prepare to stop', 'Speed up to clear junction', 'Yield only', 'For emergency vehicles'], 0, 'easy', 'An amber light means prepare to stop — the light is about to turn red.'),
            $q($rs, 'A green arrow traffic light means:', ['You may proceed in that direction', 'All traffic may go', 'Pedestrians may cross', 'Emergency vehicles only'], 0, 'medium', 'A green filter arrow allows traffic to move in the indicated direction.'),
            $q($rs, 'What does a flashing amber traffic light mean?', ['Proceed with caution', 'Stop immediately', 'Lights are broken — treat as stop', 'Give way to all traffic'], 0, 'medium', 'A flashing amber light means proceed carefully — exercise caution.'),
            $q($rs, 'A "Keep Left" sign in a blue circle means:', ['You must keep to the left side', 'Left turn recommended', 'One-way left only', 'Left lane closed'], 0, 'easy', 'Blue circle keep-left signs are mandatory — you must pass to the left.'),

            // ── TRAFFIC RULES (80 questions) ────────────────────────────────
            $q($tr, 'What is the general speed limit in a residential area in Rwanda?', ['40 km/h', '60 km/h', '80 km/h', '30 km/h'], 0, 'medium', 'In Rwanda, built-up areas and residential zones have a speed limit of 40 km/h.'),
            $q($tr, 'When should you use your hazard lights?', ['When your vehicle is broken down or stationary', 'When driving in rain', 'When overtaking', 'When you are late'], 0, 'easy', 'Hazard lights warn other drivers of a stationary or broken-down vehicle.'),
            $q($tr, 'Who has the right of way at an unmarked intersection?', ['The vehicle on the right', 'The vehicle on the left', 'The faster vehicle', 'The larger vehicle'], 0, 'medium', 'At unmarked intersections, the vehicle coming from the right has priority.'),
            $q($tr, 'At a roundabout, who has priority?', ['Traffic already in the roundabout', 'Vehicles approaching the roundabout', 'Larger vehicles', 'The first to arrive'], 0, 'easy', 'Traffic already circulating in a roundabout has priority over entering vehicles.'),
            $q($tr, 'What is the minimum following distance recommended at 80 km/h?', ['At least 40 metres (2-second rule)', '10 metres', '5 metres', '1 car length'], 0, 'medium', 'The 2-second rule: leave at least 2 seconds of following distance behind the car ahead.'),
            $q($tr, 'When overtaking, you should:', ['Only overtake when it is safe and legal', 'Always overtake on the right side', 'Flash lights and honk first', 'Speed up past the vehicle quickly'], 0, 'easy', 'Overtaking must only occur when the road ahead is clear and it is legal to do so.'),
            $q($tr, 'Where is overtaking prohibited?', ['On bends, hills, pedestrian crossings, and junctions', 'On straight roads only', 'At night only', 'On motorways only'], 0, 'medium', 'Overtaking is dangerous and prohibited near bends, hills, crossings, and junctions.'),
            $q($tr, 'What should you do when an emergency vehicle with sirens approaches?', ['Pull over to the left and stop to let it pass', 'Speed up to clear the road', 'Ignore it if you have right of way', 'Follow it closely'], 0, 'easy', 'Always give way to emergency vehicles — pull left and stop safely.'),
            $q($tr, 'When can you use your horn?', ['To warn other road users of danger', 'To greet someone', 'To express frustration', 'Whenever you feel like it'], 0, 'easy', 'The horn should only be used to warn others of your presence or a hazard.'),
            $q($tr, 'What is the blood alcohol limit for drivers in Rwanda?', ['0.08% (80 mg/100ml)', '0.05%', '0.10%', 'Zero tolerance'], 0, 'medium', 'Rwanda law sets the legal blood alcohol concentration limit at 0.08% (80mg/100ml).'),
            $q($tr, 'Can you use a mobile phone while driving?', ['No, it is illegal unless using hands-free', 'Yes, if driving slowly', 'Yes, only for calls not texts', 'Only at red lights'], 0, 'easy', 'Using a handheld phone while driving is illegal — use hands-free only.'),
            $q($tr, 'How close to a junction can you park?', ['No closer than 10 metres', '5 metres', '2 metres', 'At the kerb only'], 0, 'medium', 'Parking within 10 metres of a junction obstructs visibility and is illegal.'),
            $q($tr, 'What does double yellow lines on the road mean?', ['No parking or waiting at any time', 'Parking allowed briefly', 'Loading zone only', 'No stopping'], 0, 'medium', 'Double yellow lines prohibit waiting or parking at any time.'),
            $q($tr, 'When must you dip (lower) your headlights?', ['When approaching or following another vehicle', 'Only when it is raining', 'At all times at night', 'Only on motorways'], 0, 'easy', 'Dip headlights (use low beam) when approaching oncoming traffic or following closely.'),
            $q($tr, 'A driver must always carry:', ['Valid driving licence and registration documents', 'Insurance certificate only', 'Passport', 'Mobile phone'], 0, 'medium', 'Drivers must carry their driving licence and vehicle registration at all times.'),
            $q($tr, 'What is the speed limit on a national highway in Rwanda?', ['80 km/h', '100 km/h', '120 km/h', '60 km/h'], 0, 'medium', 'National highways in Rwanda have a speed limit of 80 km/h.'),
            $q($tr, 'You must stop for how long at a STOP sign?', ['Until safe to proceed — completely stop first', '3 seconds minimum', '5 seconds', 'Briefly slow down'], 0, 'medium', 'A STOP sign requires a complete stop; you may proceed only when it is safe.'),
            $q($tr, 'Seat belts must be worn by:', ['All occupants of the vehicle', 'Driver only', 'Front seat passengers only', 'Adults only'], 0, 'easy', 'All vehicle occupants are legally required to wear seatbelts.'),
            $q($tr, 'When can you drive in a bus lane?', ['Only during permitted hours or when the sign allows', 'Whenever the lane is empty', 'Only if driving a minibus', 'Never'], 0, 'medium', 'Bus lanes may allow certain vehicles during specified times — check signage.'),
            $q($tr, 'What does "right of way" mean?', ['The entitlement to proceed before others', 'Driving on the right side', 'The right lane', 'Priority parking'], 0, 'easy', 'Right of way is the legal priority to proceed at junctions and crossings.'),
            $q($tr, 'Driving without a licence is:', ['A serious criminal offence', 'Only a minor infringement', 'Allowed in rural areas', 'Permitted with a learner permit unsupervised'], 0, 'easy', 'Driving without a valid licence is a criminal offence in Rwanda.'),
            $q($tr, 'What should you do when a school bus is stopped with flashing lights?', ['Stop and wait until children are safe', 'Slow to 20 km/h', 'Pass quickly on the far side', 'Honk to notify children'], 0, 'easy', 'When a school bus is loading or unloading, you must stop for safety.'),
            $q($tr, 'Which lane should you use on a multi-lane road when not overtaking?', ['The left (nearest to kerb) lane', 'The middle lane', 'Any lane', 'The right lane'], 0, 'medium', 'Keep left unless overtaking — always return to the left lane after passing.'),
            $q($tr, 'What must you do before changing lanes?', ['Check mirrors, signal, check blind spot', 'Signal only', 'Check mirrors only', 'Speed up first'], 0, 'easy', 'Always mirror-signal-manoeuvre: check mirrors, signal intention, check blind spot.'),
            $q($tr, 'Driving whilst fatigued is:', ['As dangerous as drink driving', 'Only risky at night', 'Less dangerous than drink driving', 'Only an issue on long trips'], 0, 'medium', 'Fatigue seriously impairs reaction time and judgement, similar to alcohol impairment.'),
            $q($tr, 'What is the rule for cyclists and motorcyclists at junctions?', ['Give way to them as you would other vehicles', 'They must always give way', 'They have no right of way', 'Sound horn to alert them'], 0, 'medium', 'Cyclists and motorcyclists have the same rights as other road users at junctions.'),
            $q($tr, 'How should you position your vehicle when turning right?', ['Move to the centre of the road when safe', 'Stay in the left lane', 'Use the right kerb', 'Signal and turn from any position'], 0, 'medium', 'For right turns, position close to the centre line and signal in advance.'),
            $q($tr, 'What must you do if you are involved in a road accident?', ['Stop, give assistance, report to police', 'Drive away if minor', 'Call insurance only', 'Take photos then leave'], 0, 'easy', 'By law you must stop, render assistance, and report accidents to police.'),
            $q($tr, 'When are you required to use front fog lights?', ['In fog when visibility is less than 100m', 'Every time it rains', 'At night on unlit roads', 'During sunrise and sunset'], 0, 'medium', 'Fog lights should only be used in thick fog when visibility drops below 100 metres.'),
            $q($tr, 'What is the penalty for speeding in Rwanda?', ['Fine and possible licence suspension', 'Verbal warning only', 'Vehicle confiscation automatically', 'No penalty for first offence'], 0, 'medium', 'Speeding carries fines and repeated or serious offences may lead to licence suspension.'),
            $q($tr, 'Can you reverse on a motorway or express road?', ['No, it is strictly prohibited', 'Only in an emergency', 'Only if traffic is light', 'Yes, if careful'], 0, 'easy', 'Reversing on motorways and express roads is extremely dangerous and illegal.'),
            $q($tr, 'What does "defensive driving" mean?', ['Anticipating hazards and driving to avoid them', 'Driving aggressively to protect your lane', 'Staying in one lane at all times', 'Driving below the speed limit always'], 0, 'medium', 'Defensive driving involves anticipating danger and making decisions to stay safe.'),
            $q($tr, 'At traffic lights, when can you proceed on a red light?', ['Never, unless directed by a police officer', 'When the road is clear', 'After waiting 30 seconds', 'If there is a green filter arrow'], 2, 'medium', 'You can only proceed on red if directed by police OR if a green filter arrow is lit.'),
            $q($tr, 'A solid white line along the centre of the road means:', ['No overtaking — do not cross the line', 'Road edge marker', 'Cycle lane boundary', 'Lane reserved for buses'], 0, 'medium', 'A solid white centre line must not be crossed — overtaking is prohibited.'),
            $q($tr, 'How far in advance should you signal before turning?', ['At least 30 metres (or 3 seconds)', '5 metres', '1 metre', 'Just as you turn'], 0, 'easy', 'Signal at least 30 metres before the turning to give other road users adequate warning.'),
            $q($tr, 'Parking on a pedestrian crossing is:', ['Strictly prohibited', 'Allowed for under 2 minutes', 'Allowed if hazard lights are on', 'Allowed for loading only'], 0, 'easy', 'Parking on pedestrian crossings is always prohibited — it endangers pedestrians.'),
            $q($tr, 'What does a continuous yellow line in the centre of the road mean?', ['No overtaking in either direction', 'No parking', 'Road work ahead', 'Speed reduction zone'], 0, 'medium', 'A continuous double yellow centre line prohibits overtaking in both directions.'),
            $q($tr, 'When must you turn on your headlights?', ['At night, in poor visibility, and when required by law', 'Only at night', 'Only in fog', 'Only in tunnels'], 0, 'easy', 'Headlights are required at night, in poor visibility conditions, and in tunnels.'),
            $q($tr, 'Which vehicles must not use the overtaking lane on a motorway?', ['Heavy goods vehicles and buses', 'Motorcycles', 'Taxis', 'Emergency vehicles'], 0, 'hard', 'On motorways, heavy vehicles are generally restricted to the left lanes.'),
            $q($tr, 'What should you do if your brakes fail while driving?', ['Downshift and use the handbrake gradually', 'Pump the brakes rapidly', 'Steer into a barrier', 'Switch off the engine immediately'], 0, 'hard', 'If brakes fail: reduce speed by downshifting and apply the handbrake gently to avoid skid.'),
            $q($tr, 'Is it legal to drive in bare feet?', ['Yes, there is no law against it, but shoes are recommended', 'No, it is illegal', 'Only for automatic vehicles', 'Only in rural areas'], 0, 'hard', 'Technically legal but not recommended — your footwear should allow full brake/pedal control.'),

            // ── VEHICLE CONTROL (80 questions) ──────────────────────────────
            $q($vc, 'When driving downhill on a steep gradient, you should:', ['Use low gear and engine braking', 'Ride the clutch', 'Apply constant brake pressure', 'Put the car in neutral'], 0, 'medium', 'Use low gear to harness engine braking and avoid brake fade on steep descents.'),
            $q($vc, 'What is the correct way to hold the steering wheel?', ['At the 9 and 3 o\'clock positions', 'At 10 and 2 o\'clock', 'At 12 and 6 o\'clock', 'One hand at the top'], 0, 'medium', 'Modern guidance recommends 9 and 3 positions for best airbag safety and control.'),
            $q($vc, 'When should you use the clutch when driving a manual car?', ['When changing gears or coming to a stop', 'At all times when braking', 'Only when starting from rest', 'Whenever you slow down'], 0, 'easy', 'The clutch is used to disengage the engine when changing gears or stopping.'),
            $q($vc, 'What does ABS (Anti-lock Braking System) do?', ['Prevents wheels from locking during hard braking', 'Automatically applies brakes', 'Reduces brake pad wear', 'Increases braking distance'], 0, 'medium', 'ABS prevents wheel lock-up so you can steer while braking in an emergency.'),
            $q($vc, 'How do you correct a rear-wheel skid?', ['Steer in the direction of the skid', 'Steer in the opposite direction', 'Apply full brakes', 'Accelerate hard'], 0, 'hard', 'For oversteer/rear-wheel skid: steer into the skid (same direction rear is sliding).'),
            $q($vc, 'What is aquaplaning?', ['Tyres lose contact with road on standing water', 'Brakes overheating', 'Engine flooding', 'Window misting up'], 0, 'hard', 'Aquaplaning occurs when a film of water prevents tyres from gripping the road.'),
            $q($vc, 'Before driving off, you should always check:', ['Mirrors are adjusted and seatbelt is fastened', 'Radio is set', 'Windows are clean only', 'Lights are on'], 0, 'easy', 'Always adjust mirrors, fasten seatbelt, and check surroundings before moving.'),
            $q($vc, 'What is the recommended tyre tread depth minimum?', ['1.6 mm', '3 mm', '5 mm', '0.5 mm'], 0, 'medium', 'The legal minimum tyre tread depth is 1.6mm for safe road grip.'),
            $q($vc, 'Riding the clutch (keeping foot on clutch pedal) causes:', ['Premature clutch wear', 'Better fuel economy', 'Smoother acceleration', 'Reduced engine noise'], 0, 'medium', 'Resting your foot on the clutch pedal causes it to slip and wear prematurely.'),
            $q($vc, 'What should you do if a tyre bursts while driving?', ['Hold the wheel firmly, ease off throttle, brake gently, pull over', 'Brake hard immediately', 'Swerve to the hard shoulder', 'Accelerate to maintain control'], 0, 'hard', 'A blowout: grip wheel firmly, gradually reduce speed, steer to safety — never brake hard.'),
            $q($vc, 'Engine braking refers to:', ['Slowing using gear changes rather than brakes', 'Using the handbrake while moving', 'Pressing brake and accelerator together', 'Coasting in neutral'], 0, 'medium', 'Engine braking uses the resistance of a lower gear to slow the vehicle.'),
            $q($vc, 'When should you check your tyre pressure?', ['When tyres are cold, before a long journey', 'After every trip', 'Only when a tyre looks flat', 'Weekly regardless of temperature'], 0, 'medium', 'Check tyre pressure when cold for accurate readings — heat increases pressure.'),
            $q($vc, 'What does the oil pressure warning light indicate?', ['Low oil pressure — stop safely and check', 'Oil change reminder', 'Engine overheating', 'Gear oil low'], 0, 'medium', 'An oil pressure warning must be taken seriously — stop safely and check oil level.'),
            $q($vc, 'When parking on a hill facing uphill, you should:', ['Turn wheels away from kerb and apply handbrake', 'Turn wheels toward kerb', 'Leave in neutral', 'Leave wheels straight'], 0, 'hard', 'Facing uphill: turn wheels away from kerb so if car rolls, it hits the kerb.'),
            $q($vc, 'What is the purpose of the handbrake (parking brake)?', ['Securing the vehicle when stationary or parked', 'Emergency stopping', 'Reducing speed on descents', 'Activating ABS'], 0, 'easy', 'The handbrake holds the vehicle stationary when parked or stopped.'),
            $q($vc, 'When driving in heavy rain, you should:', ['Reduce speed and increase following distance', 'Maintain normal speed', 'Use full beam headlights', 'Drive in the centre of the road'], 0, 'easy', 'Rain reduces visibility and grip — slow down and double your following distance.'),
            $q($vc, 'Coasting (driving in neutral) is dangerous because:', ['You lose engine braking and steering response', 'It wastes fuel', 'It damages the gearbox', 'It increases speed'], 0, 'hard', 'Coasting in neutral removes engine braking control — dangerous especially downhill.'),
            $q($vc, 'What should you do before reversing?', ['Check all around the vehicle and use mirrors', 'Sound horn loudly', 'Turn on hazard lights', 'Switch to reverse gear quickly'], 0, 'easy', 'Before reversing, check all blind spots and use mirrors; check behind the vehicle.'),
            $q($vc, 'What does the temperature warning gauge indicate when in the red?', ['Engine is overheating — stop safely', 'Normal operating temp', 'Air conditioning issue', 'Fuel issue'], 0, 'medium', 'Red temperature gauge means the engine is dangerously hot — pull over immediately.'),
            $q($vc, 'Why is it dangerous to drive with a dirty or foggy windscreen?', ['It greatly reduces visibility and reaction time', 'It damages wipers', 'It is only illegal at night', 'It increases glare only'], 0, 'easy', 'Poor windscreen visibility is a major hazard — always ensure clear sight lines.'),
            $q($vc, 'When is it safe to remove your seatbelt while the vehicle is moving?', ['Never — seatbelt must always be worn', 'Only on slow roads', 'When reversing', 'Only for pregnant drivers'], 0, 'easy', 'Seatbelts must be worn at all times when the vehicle is in motion.'),
            $q($vc, 'What causes brake fade?', ['Overheated brakes losing effectiveness', 'Worn tyre tread', 'Clutch slipping', 'ABS activation'], 0, 'hard', 'Brake fade occurs when brakes overheat from prolonged use, reducing braking power.'),
            $q($vc, 'Correct seating position requires:', ['Knees slightly bent when fully pressing clutch, back straight', 'Arms fully extended', 'Seat reclined far back', 'Headrest at shoulder level'], 0, 'medium', 'Correct position: slight knee bend at full pedal depression, upright back, headrest at head height.'),
            $q($vc, 'What is the purpose of the fuel gauge?', ['Shows remaining fuel level', 'Measures fuel quality', 'Shows fuel injection pressure', 'Indicates optimal RPM'], 0, 'easy', 'The fuel gauge shows how much fuel remains in the tank.'),
            $q($vc, 'Which gear is used for slow, uphill driving with maximum power?', ['1st or 2nd gear', '3rd gear', '4th gear', '5th gear'], 0, 'medium', 'Lower gears (1st/2nd) provide maximum torque for climbing steep hills slowly.'),
            $q($vc, 'What does the battery warning light mean?', ['Charging system problem — get checked soon', 'Battery is fully charged', 'Needs distilled water', 'Low tyre pressure'], 0, 'medium', 'Battery warning light indicates an electrical charging system fault.'),
            $q($vc, 'When should you use full beam (high) headlights?', ['On unlit roads when no oncoming traffic', 'Always at night', 'In rain and fog', 'When driving in town'], 0, 'medium', 'Use full beam on dark unlit roads only — dip them when oncoming vehicles approach.'),
            $q($vc, 'Smooth acceleration is important because:', ['It saves fuel and reduces wear', 'It increases speed faster', 'It is required by law', 'It reduces brake usage'], 0, 'medium', 'Smooth driving reduces fuel consumption and mechanical wear on the vehicle.'),
            $q($vc, 'What is the function of a vehicle\'s differential?', ['Allows wheels to rotate at different speeds on corners', 'Controls fuel injection', 'Manages gear changes', 'Regulates engine temperature'], 0, 'hard', 'The differential allows outer wheels to travel faster than inner wheels when cornering.'),
            $q($vc, 'When driving through a flooded road, you should:', ['Drive slowly in low gear and test brakes after', 'Drive fast to avoid flooding engine', 'Avoid entirely if depth is unknown', 'Both A and C'], 3, 'hard', 'If depth is unknown, avoid flooding. If crossing, drive slowly in low gear and test brakes after.'),
            $q($vc, 'Overloading a vehicle is dangerous because:', ['It affects steering, braking, and tyre wear', 'It only reduces fuel economy', 'It is only risky on motorways', 'It voids the warranty'], 0, 'medium', 'An overloaded vehicle has poorer braking, handling, and puts tyres under excess stress.'),
            $q($vc, 'What is the correct technique for an emergency stop?', ['Apply brakes firmly and progressively, keep steering', 'Stamp brakes and hold', 'Swerve and brake simultaneously', 'Shift to neutral first'], 0, 'hard', 'Apply maximum brake force progressively; with ABS you can steer while braking hard.'),
            $q($vc, 'What is "left-hand traffic"?', ['Driving on the left side of the road', 'Left-hand drive vehicles', 'Overtaking on the left', 'Keeping left at junctions'], 0, 'medium', 'Rwanda and many African countries use left-hand traffic — vehicles drive on the left.'),
            $q($vc, 'A vehicle pulls to one side when braking. This indicates:', ['Uneven braking, worn brake pads, or tyre issue', 'Normal vehicle behaviour', 'Wheel alignment only', 'Low fuel'], 0, 'medium', 'Pulling to one side under braking signals brake, tyre, or alignment problems.'),
            $q($vc, 'What does "heel-and-toe" technique refer to?', ['Simultaneous braking and downshifting technique', 'Foot position when reversing', 'Emergency brake technique', 'Parking on hills'], 0, 'hard', 'Heel-and-toe is a performance driving technique to match revs while braking and downshifting.'),
            $q($vc, 'How often should engine oil be checked?', ['At least monthly and before long journeys', 'Once per year', 'Only at service intervals', 'After every 100 km'], 0, 'easy', 'Check oil monthly and before long journeys — oil level is critical to engine health.'),
            $q($vc, 'The purpose of power steering is to:', ['Make steering easier at low speeds', 'Improve fuel efficiency', 'Increase maximum speed', 'Replace the steering column'], 0, 'easy', 'Power steering reduces driver effort, especially when manoeuvring at low speeds.'),
            $q($vc, 'If your accelerator (throttle) sticks while driving, you should:', ['Switch to neutral and brake to a safe stop', 'Switch off ignition immediately', 'Apply brakes while in gear', 'Open the door and jump out'], 0, 'hard', 'If throttle sticks: shift to neutral, brake safely to a stop, then switch off engine.'),
            $q($vc, 'What is the three-point turn?', ['A method to reverse direction in a confined space', 'Turning at a crossroads', 'A U-turn on a motorway', 'A parking technique'], 0, 'easy', 'The three-point turn (K-turn) reverses direction using forward-reverse-forward movements.'),
            $q($vc, 'What does the RPM gauge (tachometer) show?', ['Engine revolutions per minute', 'Speed in km/h', 'Gear position', 'Fuel consumption'], 0, 'easy', 'The tachometer shows how fast the engine is spinning in revolutions per minute.'),
            $q($vc, 'When is it appropriate to use the highest gear?', ['At cruising speed on open roads', 'In heavy traffic', 'Going uphill', 'Starting from rest'], 0, 'easy', 'Top gear is used at steady cruising speeds for maximum fuel efficiency.'),

            // ── ROAD SAFETY (80 questions) ──────────────────────────────────
            $q($safety, 'What is the most common cause of road accidents?', ['Human error (distracted, speeding, drunk driving)', 'Vehicle mechanical failure', 'Poor road design', 'Bad weather alone'], 0, 'easy', 'Over 90% of road accidents are caused or contributed to by human error.'),
            $q($safety, 'How does alcohol affect driving ability?', ['Impairs judgment, slows reaction time, reduces coordination', 'Improves confidence and alertness', 'Has no effect in small amounts', 'Only impairs vision'], 0, 'easy', 'Alcohol impairs multiple driving skills: judgment, reaction time, coordination, and vision.'),
            $q($safety, 'What is the "two-second rule" used for?', ['Maintaining safe following distance', 'Braking distance at high speed', 'Signalling timing', 'Overtaking safely'], 0, 'easy', 'The two-second rule helps maintain a safe gap from the vehicle ahead.'),
            $q($safety, 'Children in vehicles should be:', ['Secured in appropriate child seats or booster seats', 'Held by an adult', 'Seated in the rear using adult seatbelt', 'Allowed to stand if space is needed'], 0, 'easy', 'Children must use age-appropriate child restraints for proper crash protection.'),
            $q($safety, 'What is a "black spot" on the road?', ['A location with a high rate of accidents', 'A poorly lit area', 'A speed camera location', 'A road surface defect'], 0, 'medium', 'Black spots are locations with above-average accident rates requiring extra caution.'),
            $q($safety, 'Texting while driving increases accident risk by:', ['Up to 23 times compared to undistracted driving', '2 times', '5 times', 'No significant increase'], 0, 'medium', 'Research shows texting while driving raises collision risk by up to 23 times.'),
            $q($safety, 'What should you do when approaching a zebra crossing with pedestrians waiting?', ['Slow down and stop to let them cross', 'Flash lights to signal them to wait', 'Proceed if they are still on the pavement', 'Honk to make them aware'], 0, 'easy', 'Drivers must give way to pedestrians at zebra crossings.'),
            $q($safety, 'At what distance should you be able to read a number plate?', ['20 metres in good daylight', '10 metres', '50 metres', '5 metres'], 0, 'medium', 'If you cannot read a number plate at 20 metres, your vision is unsafe for driving.'),
            $q($safety, 'What is the biggest risk when driving long distances?', ['Driver fatigue and microsleep', 'Fuel running out', 'Tyre pressure changes', 'Engine overheating'], 0, 'medium', 'Long-distance fatigue causes microsleep episodes that can be fatal.'),
            $q($safety, 'How should you treat a cyclist on the road?', ['As you would any other vehicle — give space and respect', 'Always overtake quickly', 'Use horn to alert them', 'Drive close to monitor them'], 0, 'easy', 'Cyclists are vulnerable road users — give at least 1.5 metres when overtaking.'),
            $q($safety, 'The correct action when your vehicle breaks down on a motorway is:', ['Pull over to hard shoulder, use hazard lights, place warning triangle', 'Stop in your lane with hazard lights', 'Stay with vehicle in traffic lane', 'Wait for other drivers to stop'], 0, 'medium', 'Move to hard shoulder, use hazard lights, triangle behind vehicle, stand behind barrier.'),
            $q($safety, 'Night driving is more dangerous because:', ['Reduced visibility and increased glare from headlights', 'Roads are more slippery', 'Traffic is heavier', 'Speed limits increase'], 0, 'easy', 'Night reduces your field of vision, depth perception, and peripheral vision significantly.'),
            $q($safety, 'What is the purpose of a reflective triangle (warning triangle)?', ['To warn other drivers of a stationary vehicle', 'To mark parking spaces', 'To indicate road works', 'To signal a right turn'], 0, 'easy', 'Warning triangles alert approaching drivers to a hazard or broken-down vehicle.'),
            $q($safety, 'Why should you not drive immediately after waking up?', ['Sleep inertia impairs alertness and reaction time', 'It is illegal before 6am', 'Visibility is poor', 'Roads are more dangerous at dawn'], 0, 'hard', 'Sleep inertia causes grogginess that impairs driving ability for up to 30 minutes.'),
            $q($safety, 'What percentage of serious accidents involve speeding?', ['Approximately 30%', '5%', '10%', 'Over 80%'], 0, 'hard', 'Speed is a factor in roughly 30% of fatal and serious road accidents globally.'),
            $q($safety, 'When should you stop driving and rest?', ['Every 2 hours on long journeys', 'Every 5 hours', 'Only when you feel very tired', 'Once per journey'], 0, 'medium', 'Take a 15-minute break every 2 hours to prevent fatigue on long drives.'),
            $q($safety, 'What is the best protection against whiplash in a rear collision?', ['Properly adjusted head restraint (headrest)', 'Wearing seatbelt', 'Sitting far from the seat back', 'Wearing a helmet'], 0, 'medium', 'A correctly adjusted headrest reduces whiplash by limiting neck movement in rear impacts.'),
            $q($safety, 'What is the safest thing to do in adverse weather (heavy storm)?', ['Reduce speed, increase gap, use appropriate lights', 'Maintain normal speed to arrive sooner', 'Turn off lights to avoid glare', 'Drive in the centre to avoid edge water'], 0, 'easy', 'In poor weather: slow down, increase following distance, and use appropriate lighting.'),
            $q($safety, 'Using a hands-free phone while driving:', ['Is still distracting and risky', 'Is completely safe', 'Is legal and safe', 'Is safer than a hand-held phone with no risk'], 0, 'medium', 'Even hands-free calls cause cognitive distraction — risk remains, though it is legal.'),
            $q($safety, 'What should you do when a pedestrian steps into your path unexpectedly?', ['Brake firmly and sound horn if needed', 'Swerve immediately', 'Accelerate past them', 'Flash high beams'], 0, 'easy', 'Apply brakes firmly and use horn if necessary — swerving can cause worse accidents.'),
            $q($safety, 'Aggressive driving (tailgating, cutting off) is dangerous because:', ['It reduces reaction time and provokes dangerous responses', 'It only affects the aggressive driver', 'It is only illegal on motorways', 'It is fine if traffic is light'], 0, 'easy', 'Aggressive driving reduces safety margins and can provoke dangerous reactions from others.'),
            $q($safety, 'What is road rage?', ['Angry, violent behaviour by a driver triggered by other road users', 'Fatigue-induced errors', 'A type of mechanical failure', 'Legal assertive driving'], 0, 'easy', 'Road rage is aggressive driving behaviour driven by anger that endangers all road users.'),
            $q($safety, 'Why are motorcyclists particularly vulnerable?', ['They have no protective shell around them', 'They drive too fast', 'They are harder to see at day', 'They do not follow rules'], 0, 'easy', 'Motorcyclists lack the structural protection of a car — injuries in crashes are far more severe.'),
            $q($safety, 'What should pedestrians do at night?', ['Wear bright or reflective clothing', 'Walk in the middle of the road', 'Stay on unlit paths', 'Avoid roads entirely'], 0, 'easy', 'Reflective or light-coloured clothing makes pedestrians visible to drivers at night.'),
            $q($safety, 'How does rain affect stopping distance?', ['Increases it by up to double', 'Has no effect with ABS', 'Reduces it slightly', 'Only affects stopping on hills'], 0, 'medium', 'Wet roads reduce tyre friction, significantly increasing stopping distance.'),
            $q($safety, 'What is the safest position when stopped at traffic lights at night?', ['Leave enough room to see the rear tyres of the car ahead', 'As close as possible to the car ahead', 'Right at the stop line', 'In the middle of the road'], 0, 'medium', 'Stopping with a visible gap protects you from being pushed into cross-traffic if rear-ended.'),
            $q($safety, 'Loading a roof rack affects driving by:', ['Raising centre of gravity and increasing wind resistance', 'Improving stability', 'Reducing fuel consumption', 'Having no effect at highway speed'], 0, 'medium', 'A loaded roof rack raises the centre of gravity and increases drag and fuel consumption.'),
            $q($safety, 'In a collision, seatbelts:', ['Prevent ejection and distribute crash forces', 'Can cause injury and should be avoided', 'Only help at high speed', 'Are only effective in frontal impacts'], 0, 'easy', 'Seatbelts keep occupants in the vehicle and spread crash forces over strong body areas.'),
            $q($safety, 'What does "stopping distance" include?', ['Thinking distance + braking distance', 'Braking distance only', 'Distance from hazard to swerve', 'Reaction time only'], 0, 'medium', 'Total stopping distance = thinking distance (reaction time) + braking distance.'),
            $q($safety, 'The most dangerous time to drive in terms of glare is:', ['Sunrise and sunset', 'Midnight', 'Mid-afternoon', 'Morning rush hour'], 0, 'medium', 'Low sun angle at sunrise and sunset creates severe glare that reduces visibility.'),
            $q($safety, 'What does a speed bump (road hump) achieve?', ['Forces traffic to slow down in areas with vulnerable road users', 'Damages tyres of speeding cars', 'Is only decorative', 'Reduces road noise'], 0, 'easy', 'Speed bumps physically force traffic to reduce speed near schools, crossings, and estates.'),
            $q($safety, 'Driving with earphones or headphones is dangerous because:', ['It blocks important audio cues like horns and sirens', 'It is always illegal', 'It reduces vision', 'Only stereo headphones are dangerous'], 0, 'medium', 'Blocking audio cues prevents drivers from hearing emergency vehicles and warnings.'),
            $q($safety, 'What increases fuel consumption most?', ['High speed and rapid acceleration', 'Smooth driving', 'City driving at low speed', 'Air conditioning alone'], 0, 'medium', 'High speeds create exponentially more aerodynamic drag; rapid acceleration wastes fuel.'),
            $q($safety, 'If you miss your exit on a motorway, you should:', ['Continue to the next exit and turn around', 'Reverse to the exit', 'Stop on the hard shoulder and wait', 'Cross the central reservation'], 0, 'easy', 'Never reverse on a motorway — continue to the next junction and double back.'),
            $q($safety, 'The purpose of road markings (lines, arrows) is to:', ['Guide, warn, and regulate traffic', 'Decorate the road', 'Mark drainage channels', 'Show road ownership'], 0, 'easy', 'Road markings guide traffic flow, warn of hazards, and enforce regulations.'),
            $q($safety, 'What is the correct sequence when approaching a hazard?', ['Mirror, Signal, Brake, Gear, Steer', 'Brake, Steer, Signal', 'Signal, Brake, Mirror', 'Accelerate, Signal, Steer'], 0, 'medium', 'MSBGS: Mirror → Signal → Brake → select appropriate Gear → Steer through the hazard.'),
            $q($safety, 'Children are at higher risk as pedestrians because:', ['They are unpredictable and have poor hazard perception', 'They always follow adults', 'They are more visible', 'They have faster reflexes'], 0, 'easy', 'Children lack mature hazard perception and can dart into the road unexpectedly.'),
            $q($safety, 'A safe following distance in ideal conditions at 60 km/h is:', ['At least 33 metres (2-second gap)', '10 metres', '5 metres', '1 car length'], 0, 'medium', 'At 60 km/h, a 2-second gap equals roughly 33 metres of following distance.'),
            $q($safety, 'What is the correct way to merge onto a highway from a slip road?', ['Match the speed of highway traffic, then merge smoothly', 'Stop and wait for a large gap', 'Force your way in', 'Drive slowly to be cautious'], 0, 'medium', 'Accelerate on the slip road to match highway speed, then merge into a safe gap.'),
            $q($safety, 'What makes rural roads particularly dangerous?', ['No central barrier, narrow lanes, animals, cyclists, and varied surfaces', 'Higher speed limits', 'More traffic', 'Poor lighting only'], 0, 'medium', 'Rural roads lack barriers, have varied hazards, and higher-speed accidents are more fatal.'),

            // ── FIRST AID & EMERGENCIES (80 questions) ──────────────────────
            $q($fa, 'What is the first action at an accident scene?', ['Ensure your own safety, then call emergency services', 'Move all injured persons immediately', 'Start CPR immediately', 'Take photographs'], 0, 'easy', 'Never rush in unsafely — assess the scene, call 112, then render assistance.'),
            $q($fa, 'The emergency number in Rwanda is:', ['112', '999', '911', '0800 100'], 0, 'easy', 'In Rwanda, dial 112 for police, ambulance, and fire emergency services.'),
            $q($fa, 'CPR stands for:', ['Cardiopulmonary Resuscitation', 'Critical Patient Response', 'Crash Prevention Response', 'Cardiac Pump Renewal'], 0, 'easy', 'CPR (Cardiopulmonary Resuscitation) combines chest compressions and rescue breaths.'),
            $q($fa, 'The correct ratio of chest compressions to rescue breaths in adult CPR is:', ['30:2', '15:2', '5:1', '10:2'], 0, 'medium', 'Standard adult CPR: 30 chest compressions to every 2 rescue breaths.'),
            $q($fa, 'How deep should chest compressions be in adult CPR?', ['5–6 cm (about 2 inches)', '1–2 cm', '10 cm', 'As hard as possible'], 0, 'medium', 'Effective chest compressions must be 5–6 cm deep to circulate blood adequately.'),
            $q($fa, 'What is the recovery position used for?', ['Unconscious, breathing casualty — prevents choking on vomit', 'All injured persons', 'Casualties with back injuries', 'CPR follow-up only'], 0, 'medium', 'Recovery position keeps the airway open for unconscious, breathing casualties.'),
            $q($fa, 'How should you control severe external bleeding?', ['Apply firm, direct pressure with a clean cloth', 'Apply a tourniquet immediately', 'Elevate and ignore if minor', 'Rinse wound with water first'], 0, 'easy', 'Direct firm pressure is the primary method to control external bleeding.'),
            $q($fa, 'An injured person should be moved from a vehicle when:', ['There is immediate danger (fire, flooding) only', 'They are unconscious', 'They are in pain', 'Always to check for injuries'], 0, 'medium', 'Move a casualty only if they face immediate life-threatening danger — movement can worsen injuries.'),
            $q($fa, 'What is the ABC of first aid?', ['Airway, Breathing, Circulation', 'Alert, Bleed, Call', 'Assess, Bandage, Compressions', 'Airway, Bruise, Calm'], 0, 'easy', 'ABC: ensure Airway is clear, check Breathing, assess Circulation (pulse/bleeding).'),
            $q($fa, 'A casualty is unconscious but breathing. You should:', ['Place in recovery position and monitor', 'Start CPR', 'Give them water', 'Leave them and call for help only'], 0, 'easy', 'Breathing unconscious casualties go in recovery position to protect their airway.'),
            $q($fa, 'To open a casualty\'s airway, you:', ['Tilt head back and lift chin', 'Turn head to the side', 'Push head forward', 'Press on chest'], 0, 'easy', 'Head-tilt chin-lift opens the airway by straightening the throat passage.'),
            $q($fa, 'What does "catastrophic haemorrhage" mean?', ['Life-threatening severe bleeding', 'Minor cuts and bruises', 'Internal bleeding only', 'Head injuries'], 0, 'medium', 'Catastrophic haemorrhage is massive, life-threatening external blood loss requiring immediate control.'),
            $q($fa, 'How do you check if a person is unconscious?', ['Shout and gently shake their shoulder', 'Pour water on their face', 'Slap them firmly', 'Check their pupils only'], 0, 'easy', 'Shout the person\'s name and gently shake their shoulders to check responsiveness.'),
            $q($fa, 'You should call emergency services BEFORE or AFTER starting CPR?', ['Call first, then start CPR (or shout for someone to call)', 'Always CPR first', 'Call after completing first cycle', 'Only call if CPR fails'], 0, 'medium', 'If alone: call 112 first, then start CPR. With others: one calls while other starts CPR.'),
            $q($fa, 'When you suspect a spinal injury, you should:', ['Keep the head/neck still and do not move the casualty unless necessary', 'Sit them up to check breathing', 'Bend their neck gently', 'Apply firm pressure to the spine'], 0, 'easy', 'Suspected spinal injuries require minimal movement to prevent permanent paralysis.'),
            $q($fa, 'A first aid kit in a vehicle should include:', ['Gloves, bandages, sterile dressings, scissors, CPR face shield', 'Only plasters and paracetamol', 'Antibiotics and painkillers', 'Just a bandage'], 0, 'easy', 'A vehicle kit should include PPE gloves, various dressings, scissors, and a face shield.'),
            $q($fa, 'For a burn injury, the first action is:', ['Cool with running water for at least 20 minutes', 'Apply butter or oil', 'Burst any blisters', 'Wrap tightly in bandage'], 0, 'easy', 'Cool burns with running cool water for 20 minutes to reduce tissue damage.'),
            $q($fa, 'What is a tourniquet used for?', ['To stop life-threatening limb bleeding when direct pressure fails', 'Minor cuts', 'All bleeding injuries', 'Restricting movement'], 0, 'medium', 'A tourniquet is applied above a wound to stop severe limb bleeding as a last resort.'),
            $q($fa, 'How do you treat suspected broken bones?', ['Immobilise and support the injured limb, do not straighten', 'Straighten the limb gently', 'Massage the area', 'Apply heat'], 0, 'easy', 'For fractures: immobilise the limb as found, support it, and seek emergency help.'),
            $q($fa, 'What is shock (medical) in trauma?', ['Inadequate blood flow to vital organs', 'Emotional distress only', 'Loss of consciousness', 'High blood pressure'], 0, 'medium', 'Medical shock means vital organs are not getting enough blood — a life-threatening emergency.'),
            $q($fa, 'Signs of shock include:', ['Pale, cold, clammy skin; rapid weak pulse; confusion', 'Flushed red face and high energy', 'Raised temperature and sweating only', 'Loud breathing only'], 0, 'medium', 'Shock signs: pale/cold/clammy skin, weak rapid pulse, shallow breathing, confusion.'),
            $q($fa, 'If a person is in shock, you should:', ['Lay them flat, raise legs if no injury allows, keep warm, monitor', 'Give them water to drink', 'Sit them upright', 'Apply cold compresses to the body'], 0, 'medium', 'For shock: lay flat, elevate legs (if no injury), keep warm, monitor, await ambulance.'),
            $q($fa, 'What does AED stand for?', ['Automated External Defibrillator', 'Airway Emergency Device', 'Advanced Emergency Diagnostic', 'Arterial Emergency Dressing'], 0, 'medium', 'An AED delivers an electric shock to restore normal heart rhythm in cardiac arrest.'),
            $q($fa, 'A person is choking and cannot cough effectively. You should:', ['Give up to 5 back blows, then up to 5 abdominal thrusts', 'Give water immediately', 'Lay them flat', 'Do nothing — it will clear itself'], 0, 'medium', 'First aid for choking: 5 back blows between shoulder blades, then 5 abdominal thrusts.'),
            $q($fa, 'What should you do if someone has a nosebleed?', ['Sit them forward, pinch soft part of nose for 10 minutes', 'Tilt head back', 'Plug with cotton firmly', 'Lay them flat'], 0, 'easy', 'Lean forward to prevent swallowing blood; pinch the soft nose for 10 minutes.'),
            $q($fa, 'Hypothermia (extreme cold) is treated by:', ['Warming gradually with blankets in a shelter', 'Rubbing vigorously to generate heat', 'Cold water immersion', 'Giving hot drinks immediately'], 0, 'medium', 'Gradual rewarming with blankets in a warm environment — avoid vigorous rubbing or hot water.'),
            $q($fa, 'If someone has swallowed poison, you should:', ['Call emergency services and do NOT induce vomiting', 'Make them vomit immediately', 'Give milk to neutralise it', 'Wait to see if symptoms appear'], 0, 'hard', 'Never induce vomiting after poisoning — call emergency services immediately for guidance.'),
            $q($fa, 'What does "triage" mean at a mass casualty incident?', ['Sorting casualties by severity to prioritise treatment', 'Treating all casualties equally', 'Transporting casualties', 'Documenting injuries'], 0, 'hard', 'Triage categorises casualties so limited resources go to those who can most benefit.'),
            $q($fa, 'An asthma attack is treated with:', ['Their prescribed inhaler (reliever/blue inhaler)', 'Paper bag breathing', 'Laying them flat', 'Tight chest binding'], 0, 'medium', 'An asthma reliever inhaler (usually blue salbutamol) opens the airways during an attack.'),
            $q($fa, 'What are the signs of a diabetic emergency (hypoglycaemia)?', ['Pale, sweaty, shaking, confused, hungry', 'Flushed, slow pulse, deep breathing', 'Drowsy with sweet breath only', 'No obvious signs'], 0, 'medium', 'Hypoglycaemia (low blood sugar): pale, sweaty, shaking, confused, hungry, aggressive.'),
            $q($fa, 'For an epileptic seizure, you should:', ['Protect from injury, cushion head, do not restrain or put anything in mouth', 'Hold them down firmly', 'Put something in their mouth', 'Give water during seizure'], 0, 'medium', 'During a seizure: clear space, cushion head, do not restrain, never put anything in mouth.'),
            $q($fa, 'The "golden hour" in trauma refers to:', ['The first hour after serious injury when rapid treatment is most critical', 'Best time to call an ambulance', 'Fastest route to hospital', 'Time for CPR to work'], 0, 'hard', 'The "golden hour" is the critical first 60 minutes post-injury when survival rates are highest.'),
            $q($fa, 'What does DRABC stand for in first aid assessment?', ['Danger, Response, Airway, Breathing, Circulation', 'Dress, Rest, Assess, Bandage, Compress', 'Direct, Rescue, Assess, Bleed, Communicate', 'Danger, Resuscitate, Airway, Bleed, Call'], 0, 'medium', 'DRABC is the systematic first aid approach: Danger → Response → Airway → Breathing → Circulation.'),
            $q($fa, 'After giving CPR, you should:', ['Continue until help arrives, the person recovers, or you are exhausted', 'Stop after 5 minutes', 'Stop if no pulse returns after 10 compressions', 'Rest between each cycle of 30 compressions'], 0, 'medium', 'Continue CPR until: emergency services take over, the person shows signs of life, or you are unable to continue.'),
            $q($fa, 'A head injury casualty who loses consciousness should be:', ['Treated as a spinal injury until proven otherwise', 'Sat upright', 'Given fluids', 'Left to rest undisturbed'], 0, 'medium', 'Head trauma may involve spinal injury — immobilise and treat accordingly until cleared by medics.'),
            $q($fa, 'What are warning signs of a heart attack?', ['Chest pain/pressure, shortness of breath, left arm/jaw pain, sweating', 'Headache and dizziness only', 'Nausea only', 'Sudden hunger and thirst'], 0, 'easy', 'Heart attack signs: central chest pain, arm/jaw radiation, breathlessness, sweating, nausea.'),
            $q($fa, 'Eye injuries from chemicals should be treated by:', ['Flushing with clean water for at least 20 minutes', 'Rubbing the eye', 'Applying eye drops only', 'Closing the eye and waiting'], 0, 'medium', 'Chemical eye injuries require immediate, continuous flushing with clean water for 20 minutes.'),
            $q($fa, 'For a deep penetrating wound with an object still in it, you should:', ['Leave the object in place and bandage around it', 'Remove the object immediately', 'Push it further in to stop bleeding', 'Ignore it if not bleeding heavily'], 0, 'hard', 'Never remove embedded objects — they may be preventing further bleeding. Immobilise and bandage around.'),
            $q($fa, 'When can you stop CPR for a non-breathing, pulseless casualty?', ['When emergency services arrive, person recovers, or you are physically unable to continue', 'After exactly 10 minutes', 'After 5 cycles only', 'When bystanders suggest stopping'], 0, 'medium', 'CPR must continue until professional help arrives or the casualty shows clear signs of life.'),
            $q($fa, 'The recommended compression rate for CPR is:', ['100–120 compressions per minute', '60 per minute', '150 per minute', '80 per minute'], 0, 'medium', 'Effective CPR requires 100–120 chest compressions per minute with full recoil between compressions.'),
            $q($fa, 'What should you always do before touching a casualty?', ['Ensure the scene is safe, wear gloves if available', 'Ask their name', 'Check the vehicle first', 'Remove their helmet'], 0, 'easy', 'Scene safety is paramount — never become a casualty yourself. Use gloves for infection control.'),
        ];
    }
}
